apiVersion: simplejsonapp.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: token
      name: simplejsonapp-secret
      namespace: default
    source: Secret
