## pod way

apiVersion: v1
kind: Namespace
metadata:
  name: provider-simplejsonapp

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-simplejsonapp
  namespace: provider-simplejsonapp

---
apiVersion: v1
kind: Pod
metadata:
  name: provider-simplejsonapp
  namespace: provider-simplejsonapp
spec:
  serviceAccountName: provider-simplejsonapp
  containers:
    - image: provider-simplejsonapp:v1
      imagePullPolicy: IfNotPresent
      name: provider

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-simplejsonapp-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: provider-simplejsonapp
    namespace: provider-simplejsonapp
## pod way
