apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplejsonapp
  namespace: provider-simplejsonapp
  labels:
    app: simplejsonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplejsonapp
  template:
    metadata:
      labels:
        app: simplejsonapp
    spec:
      containers:
        - name: simplejsonapp
          image: chaitanyah368/simplejsonapp:v1
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: simplejsonapp-svc
  namespace: provider-simplejsonapp
  labels:
    app: simplejsonapp
spec:
  selector:
    app: simplejsonapp
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
