apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xjsonppp.simplejsonapp.crossplane.io
spec:
  group: simplejsonapp.crossplane.io/v1alpha1
  names:
    kind: XJsonApp
    plural: XJsonApps
  claimNames:
    kind: JsonApp
    plural: JsonApps
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    age:
                      type: integer
                    designation:
                      type: string
                    location:
                      type: string
                    todos:
                      type: array
                      items:
                        type: string
                  required:
                    - name
                    - age
                    - designation
                    - location
                    - todos
              required:
                - parameters
